part of excel;

String _getScatterChartXmlString(Chart chart) =>
    '<c:scatterChart><c:scatterStyle val="lineMarker"/><c:varyColors val="0"/><c:ser><c:idx val="0"/><c:order val="0"/><c:spPr><a:ln><a:noFill/></a:ln></c:spPr><c:marker><c:symbol val="circle"/><c:size val="7"/><c:spPr><a:solidFill><a:schemeClr val="accent1"/></a:solidFill><a:ln cmpd="sng"><a:solidFill><a:schemeClr val="accent1"/></a:solidFill></a:ln></c:spPr></c:marker><c:xVal><c:numRef><c:f>${chart.seriesXRange}</c:f></c:numRef></c:xVal><c:yVal><c:numRef><c:f>${chart.seriesYRange}</c:f><c:numCache/></c:numRef></c:yVal></c:ser><c:dLbls><c:showLegendKey val="0"/><c:showVal val="0"/><c:showCatName val="0"/><c:showSerName val="0"/><c:showPercent val="0"/><c:showBubbleSize val="0"/></c:dLbls><c:axId val="910393167"/><c:axId val="1383457805"/></c:scatterChart><c:valAx><c:axId val="910393167"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:delete val="0"/><c:axPos val="b"/><c:majorGridlines><c:spPr><a:ln><a:solidFill><a:srgbClr val="B7B7B7"/></a:solidFill></a:ln></c:spPr></c:majorGridlines><c:title><c:tx><c:rich><a:bodyPr/><a:lstStyle/><a:p><a:pPr lvl="0"><a:defRPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:defRPr></a:pPr><a:r><a:rPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:rPr><a:t>${chart._series.yRange.name}</a:t></a:r></a:p></c:rich></c:tx><c:overlay val="0"/></c:title><c:numFmt formatCode="General" sourceLinked="1"/><c:majorTickMark val="none"/><c:minorTickMark val="none"/><c:tickLblPos val="nextTo"/><c:spPr><a:ln/></c:spPr><c:txPr><a:bodyPr/><a:lstStyle/><a:p><a:pPr lvl="0"><a:defRPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:defRPr></a:pPr></a:p></c:txPr><c:crossAx val="1383457805"/></c:valAx><c:valAx><c:axId val="1383457805"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:delete val="0"/><c:axPos val="l"/><c:majorGridlines><c:spPr><a:ln><a:solidFill><a:srgbClr val="B7B7B7"/></a:solidFill></a:ln></c:spPr></c:majorGridlines><c:minorGridlines><c:spPr><a:ln><a:solidFill><a:srgbClr val="CCCCCC"><a:alpha val="0"/></a:srgbClr></a:solidFill></a:ln></c:spPr></c:minorGridlines><c:title><c:tx><c:rich><a:bodyPr/><a:lstStyle/><a:p><a:pPr lvl="0"><a:defRPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:defRPr></a:pPr><a:r><a:rPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:rPr><a:t>${chart._series.xRange?.name ?? ''}</a:t></a:r></a:p></c:rich></c:tx><c:overlay val="0"/></c:title><c:numFmt formatCode="General" sourceLinked="1"/><c:majorTickMark val="none"/><c:minorTickMark val="none"/><c:tickLblPos val="nextTo"/><c:spPr><a:ln/></c:spPr><c:txPr><a:bodyPr/><a:lstStyle/><a:p><a:pPr lvl="0"><a:defRPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:defRPr></a:pPr></a:p></c:txPr><c:crossAx val="910393167"/></c:valAx>';

String _getLineChartXmlString(Chart chart, {bool filled = false}) {
  final chartTagName = filled ? 'areaChart' : 'lineChart';

  return '<c:$chartTagName><c:ser><c:idx val="0"/><c:order val="0"/><c:spPr><a:solidFill><a:srgbClr val="4285F4"><a:alpha val="30000"/></a:srgbClr></a:solidFill><a:ln cmpd="sng"><a:solidFill><a:srgbClr val="4285F4"/></a:solidFill></a:ln></c:spPr><c:cat><c:strRef><c:f>${chart.seriesXRange}</c:f></c:strRef></c:cat><c:val><c:numRef><c:f>${chart.seriesYRange}</c:f><c:numCache/></c:numRef></c:val></c:ser><c:axId val="506931242"/><c:axId val="897672871"/></c:$chartTagName><c:catAx><c:axId val="506931242"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:delete val="0"/><c:axPos val="b"/><c:title><c:tx><c:rich><a:bodyPr/><a:lstStyle/><a:p><a:pPr lvl="0"><a:defRPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:defRPr></a:pPr><a:r><a:rPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:rPr><a:t>${chart._series.xRange?.name ?? ''}</a:t></a:r></a:p></c:rich></c:tx><c:overlay val="0"/></c:title><c:numFmt formatCode="General" sourceLinked="1"/><c:majorTickMark val="none"/><c:minorTickMark val="none"/><c:spPr/><c:txPr><a:bodyPr/><a:lstStyle/><a:p><a:pPr lvl="0"><a:defRPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:defRPr></a:pPr></a:p></c:txPr><c:crossAx val="897672871"/></c:catAx><c:valAx><c:axId val="897672871"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:delete val="0"/><c:axPos val="l"/><c:majorGridlines><c:spPr><a:ln><a:solidFill><a:srgbClr val="B7B7B7"/></a:solidFill></a:ln></c:spPr></c:majorGridlines><c:minorGridlines><c:spPr><a:ln><a:solidFill><a:srgbClr val="CCCCCC"><a:alpha val="0"/></a:srgbClr></a:solidFill></a:ln></c:spPr></c:minorGridlines><c:title><c:tx><c:rich><a:bodyPr/><a:lstStyle/><a:p><a:pPr lvl="0"><a:defRPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:defRPr></a:pPr><a:r><a:rPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:rPr><a:t>${chart._series.yRange.name}</a:t></a:r></a:p></c:rich></c:tx><c:overlay val="0"/></c:title><c:numFmt formatCode="General" sourceLinked="1"/><c:majorTickMark val="none"/><c:minorTickMark val="none"/><c:tickLblPos val="nextTo"/><c:spPr><a:ln/></c:spPr><c:txPr><a:bodyPr/><a:lstStyle/><a:p><a:pPr lvl="0"><a:defRPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:defRPr></a:pPr></a:p></c:txPr><c:crossAx val="506931242"/></c:valAx>';
}

String _getPieChartXmlString(Chart chart, {bool filled = true}) {
  final chartTagName = filled ? 'pieChart' : 'doughnutChart';
  return '<c:$chartTagName><c:varyColors val="1"/><c:ser><c:idx val="0"/><c:order val="0"/><c:dPt><c:idx val="0"/><c:spPr><a:solidFill><a:srgbClr val="4285F4"/></a:solidFill></c:spPr></c:dPt><c:dPt><c:idx val="1"/><c:spPr><a:solidFill><a:srgbClr val="EA4335"/></a:solidFill></c:spPr></c:dPt><c:dPt><c:idx val="2"/><c:spPr><a:solidFill><a:srgbClr val="FBBC04"/></a:solidFill></c:spPr></c:dPt><c:dPt><c:idx val="3"/><c:spPr><a:solidFill><a:srgbClr val="34A853"/></a:solidFill></c:spPr></c:dPt><c:dPt><c:idx val="4"/><c:spPr><a:solidFill><a:srgbClr val="FF6D01"/></a:solidFill></c:spPr></c:dPt><c:dLbls><c:showLegendKey val="0"/><c:showVal val="0"/><c:showCatName val="0"/><c:showSerName val="0"/><c:showPercent val="0"/><c:showBubbleSize val="0"/><c:showLeaderLines val="1"/></c:dLbls><c:cat><c:strRef><c:f>${chart.seriesXRange}</c:f></c:strRef></c:cat><c:val><c:numRef><c:f>${chart.seriesYRange}</c:f><c:numCache/></c:numRef></c:val></c:ser><c:dLbls><c:showLegendKey val="0"/><c:showVal val="0"/><c:showCatName val="0"/><c:showSerName val="0"/><c:showPercent val="0"/><c:showBubbleSize val="0"/></c:dLbls><c:firstSliceAng val="0"/></c:$chartTagName>';
}

String _getBarChartXmlString(Chart chart, {bool horizontal = true}) {
  final barDirVal = horizontal ? 'bar' : 'col';
  final catAxPos = horizontal ? 'l' : 'b';
  final valAxPos = horizontal ? 'b' : 'l';
  final catAxOrientation = horizontal ? 'maxMin' : 'minMax';

  return '<c:barChart><c:barDir val="$barDirVal"/><c:ser><c:idx val="0"/><c:order val="0"/><c:spPr><a:solidFill><a:schemeClr val="accent1"/></a:solidFill><a:ln cmpd="sng"><a:solidFill><a:srgbClr val="000000"/></a:solidFill></a:ln></c:spPr><c:cat><c:strRef><c:f>${chart.seriesXRange}</c:f></c:strRef></c:cat><c:val><c:numRef><c:f>${chart.seriesYRange}</c:f><c:numCache/></c:numRef></c:val></c:ser><c:axId val="1875209296"/><c:axId val="547008450"/></c:barChart><c:catAx><c:axId val="1875209296"/><c:scaling><c:orientation val="$catAxOrientation"/></c:scaling><c:delete val="0"/><c:axPos val="$catAxPos"/><c:title><c:tx><c:rich><a:bodyPr/><a:lstStyle/><a:p><a:pPr lvl="0"><a:defRPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:defRPr></a:pPr><a:r><a:rPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:rPr><a:t>${chart._series.xRange?.name ?? ''}</a:t></a:r></a:p></c:rich></c:tx><c:overlay val="0"/></c:title><c:numFmt formatCode="General" sourceLinked="1"/><c:majorTickMark val="none"/><c:minorTickMark val="none"/><c:spPr/><c:txPr><a:bodyPr/><a:lstStyle/><a:p><a:pPr lvl="0"><a:defRPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:defRPr></a:pPr></a:p></c:txPr><c:crossAx val="547008450"/></c:catAx><c:valAx><c:axId val="547008450"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:delete val="0"/><c:axPos val="$valAxPos"/><c:majorGridlines><c:spPr><a:ln><a:solidFill><a:srgbClr val="B7B7B7"/></a:solidFill></a:ln></c:spPr></c:majorGridlines><c:minorGridlines><c:spPr><a:ln><a:solidFill><a:srgbClr val="CCCCCC"><a:alpha val="0"/></a:srgbClr></a:solidFill></a:ln></c:spPr></c:minorGridlines><c:title><c:tx><c:rich><a:bodyPr/><a:lstStyle/><a:p><a:pPr lvl="0"><a:defRPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:defRPr></a:pPr><a:r><a:rPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:rPr><a:t>${chart._series.yRange.name ?? ''}</a:t></a:r></a:p></c:rich></c:tx><c:overlay val="0"/></c:title><c:numFmt formatCode="General" sourceLinked="1"/><c:majorTickMark val="none"/><c:minorTickMark val="none"/><c:tickLblPos val="nextTo"/><c:spPr><a:ln/></c:spPr><c:txPr><a:bodyPr/><a:lstStyle/><a:p><a:pPr lvl="0"><a:defRPr b="0"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:latin typeface="+mn-lt"/></a:defRPr></a:pPr></a:p></c:txPr><c:crossAx val="1875209296"/></c:valAx>';
}
